#!/bin/bash

# Globbing to include hidden files (e.g. when looping through files with *)
shopt -s dotglob 

source "functions.sh"

INSTALL_DIR="${HOME}"

VERBOSE=0
FORCE=0

FILES=()
get_input_files() {
  local input="$(readlink -f $1)"
  
  # Ignore git directories
  [[ $input =~ ".git" ]] && return

  if [ -f "$input" ]; then
    FILES+=("$input")
    return
  fi

  if [ -d "$input" ]; then
    for f in $1/*; do
      echo i2 $f
      get_input_files $f
    done
  fi
}

main() {
# Handle arguments
# Taken from: http://mywiki.wooledge.org/BashFAQ/035
  while :; do
    case $1 in
    -h|-\?|--help)
      show_help
      exit 0
      ;;
    -v|--verbose)
      VERBOSE=1
      ;;
    -f|--force)
      FORCE=1
      ;;
    -d)
      if [ "$2" ]; then
        INSTALL_DIR="$2"
      else
        die_with_help "\"-d\" requires a non-empty option argument"
      fi
      shift
      ;;
    --)
      shift
      break
      ;;
    -*)
      die_with_help "Unknown option: $1"
      ;;
    *)
      break
      ;;
    esac

    shift
  done

  if [ -z "$1" ]; then
    die_with_help 'TARGET must be specified for installation'
  fi

  for f in $@; do
    if [ -e "$f" ]; then
      get_input_files $f
    else 
      die "$f does not exist"
    fi
  done

  echo FILES:
  for f in ${FILES[@]}; do
    install_config_file $f
  done
}

main "$@"
