#!/bin/bash

cleanup() {
  rm -rf $MASTER_TEMP_DIR
}

main() {
  MASTER_TEMP_DIR=$(mktemp -d /tmp/applicator.XXXXXX)
  trap cleanup EXIT
  git clone --depth 1 https://github.com/kidoge/applicator $MASTER_TEMP_DIR
  $MASTER_TEMP_DIR/applicator $@
}

main $@
